packages:
  - apps/*
  - packages/*

enableGlobalVirtualStore: false

overrides:
  deepmerge-ts: 8.0.0
  effect: 3.21.4
  expo-constants: 18.0.14
  find-my-way: 9.7.0
  js-yaml: 5.2.2
  nanoid: 3.3.18
  postcss: 8.5.25

ignoredOptionalDependencies:
  - sharp

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - bullmq@6.0.5
  - find-my-way@9.7.0
  - js-yaml@5.2.2
